### ISSUE TITLE
Cannot import things using new engineering [3.0] [We get it, stop opening new issues please!]

### ISSUE THREAD

**Issue by Geleybear** [EDCD/coriolis#205]
Tried to import [post-3.0 update] my newly-engineered ship to Coriolis via EDMC, however this error message is received when Chrome opens: 

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIACFFl1oC_-1cbW_byBH-K4aA9logIfb9Jf3kl_icnn1xLSPuN4GW1tLCFMnji6--w_33zpKyJVKiSFGOL23sBIGlaGeHu8_MPDM7q98Hd4kxgw93fpCadwM7GXwQ6t0g8PNwPDvyH9PBh98HwyDKEB8N7W9GFK_z2-It93sQ-ZMozwYfBn42ePf08md_DkIHfzv8N_7rz0fDy3-c_h3-MyzfteHExAb-CbPRnZ3OMpMM_nj3JBVXpWYzp9-6YDO16bpoM49tYpZSnVinqSqUZ83Kp5mfuBH1iYbP7y9myEya3ebT6WOzyn1kOU3n0SQPTLHih8k8yhP3202U3H8KL5Nompg0HcFn7J0d-5mNwuKTn_PszmaZDaen1gST68fYjE7MnQnH5qL4rEnOjB9ks4s8yGwcwGs3bGLTOPAfv_hB7jSRyiPoL6DZQ_kG9qQioNIm6R__EwdRah_MlUktPCvMtEHie8o9VRVJudSrPw3yf7Khyex4u3QsPFaVjgVrEHjhp-kGGZh7aFUE8hRvkHA9M8m8RSVal6al21QTTuF5ykV_-v0TWBlFCCm0_P8FRs7tbwdXj5MCJYkZ29icmwcTwAM-vV58sETI6HDy4PSZDJ7x4yZas2lMFGKaSvGMveM8AyyOFmJ-TPyJwTBnFA4-ZEkOw-LERonNHoupnx4KZkljUMMPLupAXLw_8kuJ9-UuDj6EeRC4hTiKbm8Dgwu7266ppIRj8qxpOXAE1uPmGh2DVlFg09ENWHoHjWHqEzP2A9xhYkWoWC5RMWw0jG25HV0nIt2ekNYnuox-NcklIAo2xaapf-4_2Gn4uMPM9M-Y-WMB4OMoWDislvkZkkQ_z78YnKdZNLdpucE3M5t13NjTBMQMZ_YuO0nAIfX1l6fDk89xZueA6s2ugjNP4Iq34UzgBmfxKczMtFR3g9_q7nQadHlPUVUEONYGCcW-niT-r100AQ_KWxwWRusO69QEdgwPe3DqJ6lZ91u85rdgrUfnUTi98sOp6eC1BMN06QtgbUdn8GjJxO13EdTl6DiAleINiEHPDwg-RWmMSQcfdpdORjPjPzwu3ddpboJrP7xvhzioTDmuqPw0uKRQpcK0FeJEI8oKnJ_lU3PmJ5M4smHJNnrRAn_uTzeFLgimdSiIBkiVMi5NMjTjKJzsKQyiaWJv8yxqQilZMxfJe4CdsDUxYluo94NzYG4bBDHp8aogTtqsBtF1qzlKoujg2k9-yW1Ytxhas5gb48fgFj_ewQZb4MztRiMU1po9I_AszkZHxp-f-ylE_B_t_BYg7iDVikChtdBEdbCYrFy20YNT8Nlozv3kJYB7OJ9Hx4GNnfXs6VQbbUBIj6kKbIVkq3xV9baI_qJb7cOx7How4L2Q3SceELGO7OtocvADTHVwBE4OGOYPBxfjfwHKw7bAsID55weTjGcON904LcThCtCLNOfYD0OQtYB6gcLW8MA0FhJ3gPo4SpIi_xmlMxMETWgn3zTaladqkFRqD4TvJO4N1f9TqLZ3ZpjHcZRknbgPFrrCfVbGr_I10qA6W_I1ohkucugL34ZlppD2Napy-Jnxsys_21yv0EBUqpjTmCukpAYwkya-UAqG9AHs4y4CKG6uDhDk6WoGQZBGnDBJCGEaHrVN_pb05D3zZK32AIsn3foBZeda9spUUF2oAjWVgOWAv5T0zDm0rFmjlhhDWgiUGQNWv0IGUudT5YqCG0qyx04JCNJVRC8EODCr7WBeTT6wYoIVaDYTm8-_PisSawUptmuYYGupJusdI3aQ1R4gyJow0i8-rCUrSHzN8EBeKjygtvBQoqwdlxISlA7hwYJbCyfWTx5HSZSHk3QZIGp4Jm94fsPz_xGe6fdUbmGeErVyC2Zo-YP_5OILpbXii5DfXPXF4XmlxF6tvlznSWKy7Wgmy81USmvcBc-JmZrQJGUFPTW_5KbgoQ2YZm8lxLcS4muBGBIdrdFLgNgGNgOPjfCLHowfTibWjeqw6RCW2V6n4txjtMZheCMcuxyE7ySwKX1Ua6RB7XEQ3qDSVzwLPwOAXBkbQv49NnPXVnLmDm9O8i4JnhCKM1E9YVqT5zgp357rLavmjKNuJGQG8ySVebJyfTdgnrxh_g3z3zzmYeZLHwjGP6Pb9mKhwpLqpRZPA0eL1pRT0OjCZGAnx1Ecd23BuAx8QBBYzGEcJ5E_ng1zWxb8WpZEEoplZUlKUVU5retQxvKSSSy5yX5ly_TYj_1xQ50OgEyq0MNaMaKVIkCPt5cV0ytTpmmb-pmIR6o1fUqIYlJhSoVUTYKHj5AwzrdqzKpFQFetRIRTioEpKNgKvl30y-tc0qMWnRWv6YyBImnHkjiY03bJ-6jcUhDd4ENc4n7yqwmC9m6MOk5HZ3Y6O01K6tWtOkpwtT1jTeROTRqKSIKpfLYhZ4NZX-tx5f4nzjveuK1rp0OI96mVr6UYemuKsQVomKylPuQr1MTxJhwUaz06iiIws0m3yriQ63sfF2JWquO81WtiqsBpgUV1IE3xco4ZgPXJsJ4I05U_8Xu7262HF90LfmVv0-au1frRbaMfNWEaJdfu4bLh2A8Pw2mwMfHmqupAiMfBiCrdBS0FQLnBhVg_9A9OoyTLQ1MHD6uBp1R1dGMnptSyk9vgVbdRCkl38xZaUqzLiDuc2fjTSZfuUq70Sh-sewZYzwxWvJAwOgr88X03rlGOwK8-5082G8aRDUyXhkvJhcb1tl8n5d5meLSQQ3aa_AaQmnacmjdOXUjZYWK3ap32V6OVcvLKWt-Di0gR3XW1nQT82vO6Gwq4dKJ9ndlxFAQ2hU9szVxq59LwUiONGMUKC_dMdL_cD3msypuY5owTDIulGJW9jqax8mT1LB0riZSiDHGClNgjtaS0zvOEwEwKQbBiCHHetBwAFPj1RxNuP6nHaO3aAmII8iBIhJhovHLxLH2YJeCps9kG0QqIYy2hpUCllMTwh3GxR3aLsUeqq6KUZAo4qsJA2TuwVLIh0zX24Hhm8nDaGl-ent6VBiHQLFTuFmZWHFARZmqyVmhKe0Mu5hQQoPGzhZKlhbb3BFOxQZNjoOlHT53BC0VYuyJIaQ3e9VkRuryc1a4IoxVFjoFjRFfgmla7k9vvglBB-MpSsK4aCPfD19qjh-Moijf1Ry9Gb-oQwtw9kHrWgXfVQQJBorUW7fLK2JH_uNsyYCX0oku70EGUdZMu0RGsXlV0OEkid5MizJIoGF2Z2LfJblUYLQlaqiKXqvSJH23dQfWUZ7cCHFvLmTh_aaJaz3IubDoenbuNvjHu3w6FMokJw82b5GKsGRfnFSsb1eRJ6BI1mrGVnVq5nthapSK6qs-Ru0D4BFu2HSnLQxklVufXxeAO14eQC9_VbqiTaHwPG34czeO84HcQRSAFm7SugSsZOg2ubfj4ApcbqmXu0rtuvfNIPaSrAZMiMGWOMKOaUrrn9UeP1ioLlCLGFNEu0lO1z-VH6nFck82RJkoRBZGW9LoOhDxck4kwxppCcFeQme9VHcfMI7TWsSylM2jgPYyrF2UPdCN7KKsaO3AHVyKvHYBWJTmLQdsT1ZUzUAqLuI528nW5vdtUUSP3igJzE4wBAYe93Q_jxNM1jBOllQBKqwl11rQPyJknWVU4k2CYSCpBKGG0D8oBeHWQg8VwAbEYMYXxfhhHqoZxjQUSQNQQEpjL7xbl9PV8OsZr5VNcVEgl4Upp0iPbBJ5SwwxECKwFUkX9E--BcQz2WDVPBYCUINbFn0aX23SkiYFTUVEpBTLYXeD7AHLNHIPq1bQtIEmtdeMg7W5TKsqBf8uXRTbZiuwdDzn3xTZtwzZ7PWxrT9YSfKD7hLvuSUWk0j2wTT1Na0RCw4YpIKeSEr1PJQVij6j5bwS0hxCXN0qs-a4H9pgyT1fRTRlwKUSFZpj3Ij2kKtEFMA1-AgKYBPxQRr5jZPNu2QDWFT3ckdvQhvfnxRfILHvFnOj2ksKmjEB8I3rI17R0Ubd0AT6Xc6KB3XPe54wSzJHXzZFTR8I5xhT8yI7mKGm1GRd7QOaJIgiiLKWsjzVST6qaN5IKkgTp2Crk4a9wDvptm2Tvo4COfB7StJo7ZECOwWVrDvgTe9J5XJeNIRGG3ZVYNLb3NqEPfL-sOW4qCQIbcY0vUu5H5DmrEXnGJYEg627WU_I9EHkIgaUL_AIYM8GXyI479FApwphcHoEVoy5dYfmLHbsmqE5HX2XLTOfvk6EEr3zVwWJw5ftkLvMkDjp9ocwftbNKGJMWB7TuS8um77VevLHYKogrqR8b_94s0fL7wDV1glzI-yDT5mjla70gBXE0HMN7WZT57qQDHCb4XlcOz8Mg8kPjngpDQupuQv4X7dCtg5xNAAA%3D
line: 0
col: 0
error: {}

**Comment by awdwyn** [comment]
Thanks for all the effort you guys are putting into this - it's **very** much appreciated.

**Comment by strideynet** [comment]
I've got a project that I'm currently working to finish on time, that should end this week. I will then sit down and work on the Coriolis import mechanism. Rather than continue to patch it, we are working to overhaul it for future updates.

**Comment by triccaj** [comment]
@Geleybear @awdwyn @willyb321 Can you all verify that this is now resolved? I was able to import from EDMC with all engineering making it through too.

**Comment by bjornthv** [comment]
I'm still having issues (3.0.2):

`Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAD6yp1oC_8VZ23LaSBD9lZSq9g2r5j6S3-wQx87aG5dxOY-qsRhg1kJSjSQnbMr_vi3JXCTAEuTGA8bAnO6ZPqcvw3dnYrV2TicqyvTAMWPnlIiBM0_GRaQz5_S7c2bnSWHLV_Wb5autNZh4iPlUsIETqzl85pzFKkzisQrq9cFHq8YaOwMniZ3T3BawMLUmsSZfwPKB86yiAtahl5eBc548PkYa4W6jQhJ4WhmtFwa3JkryGwXLepkb6lBFfYwJKblcGauWBR--pVFitQ3uVDzV9gCL5LdbpL_T4oUFiNHMTPKhNc-VwS-JfbqKb20ytTrLAvDETEyocpPEFdU-F_nE5LmJpxdGR-P7RaqDi9Hwc5qbuYpuVFZ9a2yyNFKLh9qWw6Tro7-clXHsMukjIjnyhedTCq7swr2Kcz2tHd-CPMGeS-QGJnI9LAlHjFLuU4TIHtA9Lp4w5CLS9BFAqOdh7Atfir1w3y4KHd1q-6mYpzuAiStkAxYRIXxCfYaFxB7fg3ubfNV2aNXXXb4S5vKmr4Rx7BEqOIaDFQiX0dXx1MRaV3lh-foKKASHgxFaf_5PzaMLHZkQDvvdhbKZrihkdWhSfa2fdeSc8uX_y--PhsF1Ek8rwjkvg67cIxgma9ZCbINL2Kgdl8wLRuY_LYL3EQSH7-EuWm-XMuRJT1YUhsO_V_FTj-QnGOWo4cBycWWe1-Zpp3Q8jDAtbV-biR4VaZrY_FjpvElx6ruSNyguUBloYBCjvpAQ5oM4LpjrNfEox0wyzBEo0ZNSsg7eAHG2eHNuoujdfWHjbcrQFmU2Diy4NtNZ_kWXz_3II5qx28Q6KHxYMIGq9HejTPyh2kx2bPzq5Zda5Xcq1zvzCnNJK_cxgihoFFNJMBB5TxBraEiskFsmiZ2rONxlgAAgb-YCzJjHPIEp1F7GOvHfSNwnspkUkesTH5THBYa_DMujMjcHlGbmZkgCLBCRef6hiVu6gjUTrBQgdCbL1gPwjkmwGHyiDVAIFCVlyCQR9Fek17ZW6vAEQ2PhFPsIBHm8IZBXgB7aWGdWJnzfr7RxC9rIPyWPvfo76ZGV6eXCYNVdnkcqfLqwZqwWAerZXt5GKta5souzNLWJCmejwtT66nSG4maVqaGaOF0-MFxlwpojJsuteSzyxPYqMgTTpv0WSBURr47IvtMgK0-49DAhK2fKzeS93ECtWlctT8vlh6XLNSXu1FjZX1Loyt4LNQvdwZWNi1ZlgxK58WB7AEc6zhJ7r-xU56NQxWfxNNqZx8mWj15XFiDbWeBam3fvZ7qIp239s5b-a8cOLpOEs0bYa5hsk3Sku8FijFNU7Q-mg_RqiLopJ7kHFWFlu9wFnF8OJ1whBF9mfYSH1jbxb7dZru-5U3-X1VurwhyEECFyjGn8B0zDEI5wRQ75K5QN9dIV_oZqiEul8BmCAYggSQXmhwkdubzZ7CBU9QxUQL_DIPsfU-095qJmCwENCZVlqyMp7az2P9gUl0PIKEyStGQt-KvH3UIX8NiouctZ5hWmjGbfWUpyLrgv1mwg9Sx2dENc3kNkMNLd6Qxq3p6mlW8lU35MJ0l4G0buw_kbogMCedOrHy5DzHd93NwWQsc0oDD5ebI1-eF91yQ1bT7quKOXF-3d7S-KS8RRboHY-WyXtFtnDy3yvrO_n2k77zj7rfoKc8xPra_t64vVHrVVZVdWHZ7J-qivLLOyqb42Wqkh2leDMA_Wl2BZCh5CANtCe30_yCorQZ4U0xmYAm_iIopW0qVr6XbeIAra7BPudKpMeX-40Rz2yB4I2kNg-NIDv1rOet1Ec-Y3PBgm4RPQ5n0yT4u8dASoAg3nuNMJKukqfWHU1wMBQ6LAzSDmOoqUPU_GC-jXw-RZ20XZE0JQg7Pxc8nccff1Qrk5vDoSXAeFHJtPh6NRUF4t3BRRvivjsPagCrM_PXCCFlvSE8eUUboFQ3-qgunuDvlCZVXn3q9qtmg_hCHTRHo8KuxEhXoZ7XsTLzojDQ0M9qomufz6JVA1TWD2pf3Yj9fsv0zzoLxCGpn46VoVcTgrXSis1flbnqwVQPz6xrfhB_tzfjwAvXX0kJiwx8juEQZJZOVEtepWhU_Bg67wezSyL1s_acGqrJoByhuJy5Oru5vXd165cz8DXqu5-tdM14T97swgnQI2ltxHntz8kQ0jjJmPBZSRPMkVfItgTzIEWh84RRwlqsrHsB-OiXx5-R-jhW8-tRsAAA%3D%3D
line: 0
col: 0
error: {}`

**Comment by willyb321** [comment]
3.0 journal imports (without engineering) are live on beta site. Engineering to follow.

**Comment by willyb321** [comment]
Ok, here's another update:

Been incredibly busy with TAFE and the like. Haven't had a lot of time to code. Also not very good at maths so if anyone wants to help try and correlate the values in the journal to the values that Coriolis uses, that would be amazing. Contact willyb321#2816 on discord if you want to help.

**Comment by triccaj** [comment]
Hey all,

Is there anyone else in the EDCD community that could help out? Feels like this is too big for 1/2 devs and tbh I think the community are making there way over the EDShipyard. I wish the solution was in C# I might have a chance at helping out - JS is too low level for me and I would likely break everything :(.

Happy to pull branches locally and test them though.

**Comment by triccaj** [comment]
Scratch that question, I'ma find them myself ;) - Will chuck out a post on reddit and see if I can get a branch worked on. Does this repo have protection on master? @strideynet @willyb321

**Comment by ralkeon** [comment]
Sorry maybe this is an obvious thing or not, but can this issue be guardian items related? My engineered ships are imported normally, but it seems that the ships with guardian tech on, will throw the error.

**Comment by willyb321** [comment]
@ralkeon no, its related to the new engineering format.

**Comment by ralkeon** [comment]
I think I found where the code breaks (can I write here where or I must pm someone?), but now I must go back to work, I'll try to take a look this evening trying to be helpful.

**Comment by willyb321** [comment]
@ralkeon the issue at the moment is trying to convert values from FDEV format to the Coriolis format, you can see [this file](https://github.com/EDCD/coriolis/blob/feature/beyond-coriolis/src/app/utils/JournalUtils.js#L234) for where the engineering effects are applied.

**Comment by ralkeon** [comment]
Yep, it seems that the problem is in the [getBlueprint](https://github.com/EDCD/coriolis/blob/6e21d0e74ac017077dbd4fe8469ffdc906e4e841/src/app/utils/BlueprintFunctions.js#L226) function: the name passed isn't the right one, but I cannot find where it is set. I found that "Sensors" (the issue in my case) are set [here](https://github.com/EDCD/coriolis/blob/6e21d0e74ac017077dbd4fe8469ffdc906e4e841/src/app/utils/CompanionApiUtils.js#L215) but I don't understand where `json.modules.Radar.module` comes from.

**Comment by willyb321** [comment]
That would be the json that is passed through the url (gzipped then b64 encoded)

**Comment by willyb321** [comment]
I have fixed this. Waiting on @Marginal to update EDMC then this will go to live. Currently on beta.

**Comment by willyb321** [comment]
This is fixed, and the EDMC update is live. Please open an issue if you have any more issues. (Make sure EDMC is up-to-date ;) )
